export const celebrities = [
  {
    id: '1',
    name: 'Elon Musk',
    match: '98%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 95},
      {label: '', value: 60},
      {label: '', value: 85},
      {label: '', value: 75},
      {label: '', value: 30},
      {label: '', value: 65},
    ],
  },
  {
    id: '2',
    name: 'Oprah Winfrey',
    match: '20%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 80},
      {label: '', value: 75},
      {label: '', value: 60},
      {label: '', value: 70},
      {label: '', value: 90},
      {label: '', value: 85},
    ],
  },
  {
    id: '3',
    name: 'Cristiano Ronaldo',
    match: '40%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 90},
      {label: '', value: 85},
      {label: '', value: 98},
      {label: '', value: 80},
      {label: '', value: 40},
      {label: '', value: 75},
    ],
  },
  {
    id: '4',
    name: 'Bill Gates',
    match: '72%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 88},
      {label: '', value: 70},
      {label: '', value: 65},
      {label: '', value: 85},
      {label: '', value: 55},
      {label: '', value: 60},
    ],
  },
  {
    id: '5',
    name: 'Michelle Obama',
    match: '68%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 75},
      {label: '', value: 80},
      {label: '', value: 70},
      {label: '', value: 65},
      {label: '', value: 85},
      {label: '', value: 90},
    ],
  },
  {
    id: '6',
    name: 'Steve Jobs',
    match: '86%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 95},
      {label: '', value: 50},
      {label: '', value: 60},
      {label: '', value: 90},
      {label: '', value: 20},
      {label: '', value: 70},
    ],
  },
  {
    id: '7',
    name: 'Serena Williams',
    match: '55%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 85},
      {label: '', value: 70},
      {label: '', value: 95},
      {label: '', value: 65},
      {label: '', value: 40},
      {label: '', value: 60},
    ],
  },
  {
    id: '8',
    name: 'Barack Obama',
    match: '62%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 80},
      {label: '', value: 70},
      {label: '', value: 60},
      {label: '', value: 75},
      {label: '', value: 75},
      {label: '', value: 85},
    ],
  },
  {
    id: '9',
    name: 'Mark Zuckerberg',
    match: '50%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 85},
      {label: '', value: 55},
      {label: '', value: 50},
      {label: '', value: 80},
      {label: '', value: 35},
      {label: '', value: 50},
    ],
  },
  {
    id: '10',
    name: 'Beyoncé',
    match: '75%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 80},
      {label: '', value: 85},
      {label: '', value: 90},
      {label: '', value: 70},
      {label: '', value: 60},
      {label: '', value: 85},
    ],
  },
  {
    id: '11',
    name: 'Taylor Swift',
    match: '65%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 75},
      {label: '', value: 80},
      {label: '', value: 60},
      {label: '', value: 65},
      {label: '', value: 70},
      {label: '', value: 85},
    ],
  },
  {
    id: '12',
    name: 'Jeff Bezos',
    match: '82%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 90},
      {label: '', value: 60},
      {label: '', value: 70},
      {label: '', value: 85},
      {label: '', value: 30},
      {label: '', value: 55},
    ],
  },
  {
    id: '13',
    name: 'Malala Yousafzai',
    match: '58%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 70},
      {label: '', value: 65},
      {label: '', value: 50},
      {label: '', value: 60},
      {label: '', value: 95},
      {label: '', value: 80},
    ],
  },
  {
    id: '14',
    name: 'Dwayne Johnson',
    match: '77%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 80},
      {label: '', value: 70},
      {label: '', value: 98},
      {label: '', value: 75},
      {label: '', value: 40},
      {label: '', value: 65},
    ],
  },
  {
    id: '15',
    name: 'Emma Watson',
    match: '60%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 70},
      {label: '', value: 65},
      {label: '', value: 55},
      {label: '', value: 60},
      {label: '', value: 80},
      {label: '', value: 85},
    ],
  },
  {
    id: '16',
    name: 'Kanye West',
    match: '30%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 65},
      {label: '', value: 50},
      {label: '', value: 75},
      {label: '', value: 45},
      {label: '', value: 25},
      {label: '', value: 40},
    ],
  },
  {
    id: '17',
    name: 'LeBron James',
    match: '73%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 85},
      {label: '', value: 75},
      {label: '', value: 95},
      {label: '', value: 70},
      {label: '', value: 50},
      {label: '', value: 65},
    ],
  },
  {
    id: '18',
    name: 'Greta Thunberg',
    match: '45%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 80},
      {label: '', value: 60},
      {label: '', value: 50},
      {label: '', value: 70},
      {label: '', value: 90},
      {label: '', value: 75},
    ],
  },
  {
    id: '19',
    name: 'Narendra Modi',
    match: '64%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 78},
      {label: '', value: 55},
      {label: '', value: 65},
      {label: '', value: 80},
      {label: '', value: 60},
      {label: '', value: 70},
    ],
  },
  {
    id: '20',
    name: 'Sundar Pichai',
    match: '88%',
    image: require('../assets/sclupture.png'),
    score: [
      {label: '', value: 85},
      {label: '', value: 65},
      {label: '', value: 60},
      {label: '', value: 85},
      {label: '', value: 55},
      {label: '', value: 60},
    ],
  },
];

export const tasksBySection = [
  {
    title: 'Morning',
    data: [
      {
        id: '1',
        name: 'Focus Timer',
        time: '7:00 AM',
        category: 'Focus',
        done: true,
      },
      {
        id: '2',
        name: 'Breakfast Freestyle',
        time: '8:00 AM',
        category: 'Nutrition',
        done: false,
      },
      {
        id: '3',
        name: 'Cold Shower Reset',
        time: '9:00 AM',
        category: 'Strength',
        done: true,
      },
      {
        id: '4',
        name: 'Morning Meditation',
        time: '6:30 AM',
        category: 'Spirituality',
        done: false,
      },
      {
        id: '5',
        name: 'Gratitude Journal',
        time: '7:30 AM',
        category: 'Mindfulness',
        done: false,
      },
    ],
  },
  {
    title: 'Afternoon',
    data: [
      {
        id: '6',
        name: 'Reset Your Day',
        time: '12:00 PM',
        category: 'Reflection',
        done: false,
      },
      {
        id: '7',
        name: 'Walk & Breathe',
        time: '1:00 PM',
        category: 'Movement',
        done: false,
      },
      {
        id: '8',
        name: 'Protein Snack',
        time: '2:30 PM',
        category: 'Nutrition',
        done: true,
      },
      {
        id: '9',
        name: 'Focus Session',
        time: '3:00 PM',
        category: 'Focus',
        done: false,
      },
      {
        id: '10',
        name: 'Hydration Break',
        time: '4:00 PM',
        category: 'Wellness',
        done: false,
      },
    ],
  },
  {
    title: 'Evening',
    data: [
      {
        id: '11',
        name: 'Evening Walk',
        time: '6:30 PM',
        category: 'Movement',
        done: false,
      },
      {
        id: '12',
        name: 'Light Dinner',
        time: '7:30 PM',
        category: 'Nutrition',
        done: true,
      },
      {
        id: '13',
        name: 'Screen Detox',
        time: '8:30 PM',
        category: 'Mindfulness',
        done: false,
      },
      {
        id: '14',
        name: 'Plan Tomorrow',
        time: '9:00 PM',
        category: 'Time Management',
        done: false,
      },
      {
        id: '15',
        name: 'Bedtime Reading',
        time: '9:30 PM',
        category: 'Focus',
        done: false,
      },
    ],
  },
];
